baseURL = "https://overholts.dev/"
languageCode = "en-us"
title = "Ben Overholts"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = -100

[permalinks]
	about = "/:filename/"